---
version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/cert.pem:/etc/cert.pem
      - /etc/key.pem:/etc/key.pem
    ports: [80:80, 443:443]
    depends_on:
      backend:
        condition: service_healthy
    networks: [backend]
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
networks:
  backend:
    driver: bridge
