---
version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/cert.pem:/etc/cert.pem
      - /etc/key.pem:/etc/key.pem
    ports: [80:80, 443:443]
    networks: [backend, certbot]
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
  certbot:
    container_name: certbot
    env_file: [.env]
    volumes: [./configs/nginx/:/etc/nginx/]
    build:
      context: ./certbot
      dockerfile: Dockerfile
      args:
        DOMAIN_EMAIL: ${DOMAIN_EMAIL}
        DOMAIN_URL: ${DOMAIN_URL}
    networks: [certbot]
networks:
  backend:
    driver: bridge
  certbot:
    driver: bridge
