---
version: '3.8'
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/nginx.conf
    ports: ['${NGINX_HTTP_PORT}:80']
    depends_on: [backend]
    networks: [backend, swagger]
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks: [backend, redis, postgres]
  swagger:
    container_name: swagger
    image: swaggerapi/swagger-ui
    environment: [SWAGGER_JSON=/docs/swagger.yml]
    volumes: [./docs:/docs]
    networks: [swagger]
  redis:
    container_name: redis
    image: redis:7.2.4
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
networks:
  backend:
    driver: bridge
  swagger:
    driver: bridge
  redis:
    driver: bridge
  postgres:
    driver: bridge
