// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.6
// source: storage/storage.proto

package service

import (
	context "context"
	status "google.golang.org/genproto/googleapis/rpc/status"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status1 "google.golang.org/grpc/status"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StorageClient is the client API for Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageClient interface {
	GetNote(ctx context.Context, in *wrapperspb.Int32Value, opts ...grpc.CallOption) (*Note, error)
	GetDir(ctx context.Context, in *wrapperspb.Int32Value, opts ...grpc.CallOption) (*Dir, error)
	CreateNote(ctx context.Context, in *Note, opts ...grpc.CallOption) (*status.Status, error)
	UpdateNote(ctx context.Context, in *NoteUpdateRequest, opts ...grpc.CallOption) (*status.Status, error)
	CreateDir(ctx context.Context, in *Dir, opts ...grpc.CallOption) (*status.Status, error)
	DeleteDir(ctx context.Context, in *wrapperspb.Int32Value, opts ...grpc.CallOption) (*status.Status, error)
	DeleteNote(ctx context.Context, in *wrapperspb.Int32Value, opts ...grpc.CallOption) (*status.Status, error)
	SearchNoteByName(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*SearchResponse, error)
	SearchNoteByBody(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*SearchResponse, error)
	SearchDir(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*SearchResponse, error)
}

type storageClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageClient(cc grpc.ClientConnInterface) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) GetNote(ctx context.Context, in *wrapperspb.Int32Value, opts ...grpc.CallOption) (*Note, error) {
	out := new(Note)
	err := c.cc.Invoke(ctx, "/Storage/GetNote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetDir(ctx context.Context, in *wrapperspb.Int32Value, opts ...grpc.CallOption) (*Dir, error) {
	out := new(Dir)
	err := c.cc.Invoke(ctx, "/Storage/GetDir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) CreateNote(ctx context.Context, in *Note, opts ...grpc.CallOption) (*status.Status, error) {
	out := new(status.Status)
	err := c.cc.Invoke(ctx, "/Storage/CreateNote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) UpdateNote(ctx context.Context, in *NoteUpdateRequest, opts ...grpc.CallOption) (*status.Status, error) {
	out := new(status.Status)
	err := c.cc.Invoke(ctx, "/Storage/UpdateNote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) CreateDir(ctx context.Context, in *Dir, opts ...grpc.CallOption) (*status.Status, error) {
	out := new(status.Status)
	err := c.cc.Invoke(ctx, "/Storage/CreateDir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) DeleteDir(ctx context.Context, in *wrapperspb.Int32Value, opts ...grpc.CallOption) (*status.Status, error) {
	out := new(status.Status)
	err := c.cc.Invoke(ctx, "/Storage/DeleteDir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) DeleteNote(ctx context.Context, in *wrapperspb.Int32Value, opts ...grpc.CallOption) (*status.Status, error) {
	out := new(status.Status)
	err := c.cc.Invoke(ctx, "/Storage/DeleteNote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) SearchNoteByName(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/Storage/SearchNoteByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) SearchNoteByBody(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/Storage/SearchNoteByBody", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) SearchDir(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/Storage/SearchDir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServer is the server API for Storage service.
// All implementations must embed UnimplementedStorageServer
// for forward compatibility
type StorageServer interface {
	GetNote(context.Context, *wrapperspb.Int32Value) (*Note, error)
	GetDir(context.Context, *wrapperspb.Int32Value) (*Dir, error)
	CreateNote(context.Context, *Note) (*status.Status, error)
	UpdateNote(context.Context, *NoteUpdateRequest) (*status.Status, error)
	CreateDir(context.Context, *Dir) (*status.Status, error)
	DeleteDir(context.Context, *wrapperspb.Int32Value) (*status.Status, error)
	DeleteNote(context.Context, *wrapperspb.Int32Value) (*status.Status, error)
	SearchNoteByName(context.Context, *wrapperspb.StringValue) (*SearchResponse, error)
	SearchNoteByBody(context.Context, *wrapperspb.StringValue) (*SearchResponse, error)
	SearchDir(context.Context, *wrapperspb.StringValue) (*SearchResponse, error)
	mustEmbedUnimplementedStorageServer()
}

// UnimplementedStorageServer must be embedded to have forward compatible implementations.
type UnimplementedStorageServer struct {
}

func (UnimplementedStorageServer) GetNote(context.Context, *wrapperspb.Int32Value) (*Note, error) {
	return nil, status1.Errorf(codes.Unimplemented, "method GetNote not implemented")
}
func (UnimplementedStorageServer) GetDir(context.Context, *wrapperspb.Int32Value) (*Dir, error) {
	return nil, status1.Errorf(codes.Unimplemented, "method GetDir not implemented")
}
func (UnimplementedStorageServer) CreateNote(context.Context, *Note) (*status.Status, error) {
	return nil, status1.Errorf(codes.Unimplemented, "method CreateNote not implemented")
}
func (UnimplementedStorageServer) UpdateNote(context.Context, *NoteUpdateRequest) (*status.Status, error) {
	return nil, status1.Errorf(codes.Unimplemented, "method UpdateNote not implemented")
}
func (UnimplementedStorageServer) CreateDir(context.Context, *Dir) (*status.Status, error) {
	return nil, status1.Errorf(codes.Unimplemented, "method CreateDir not implemented")
}
func (UnimplementedStorageServer) DeleteDir(context.Context, *wrapperspb.Int32Value) (*status.Status, error) {
	return nil, status1.Errorf(codes.Unimplemented, "method DeleteDir not implemented")
}
func (UnimplementedStorageServer) DeleteNote(context.Context, *wrapperspb.Int32Value) (*status.Status, error) {
	return nil, status1.Errorf(codes.Unimplemented, "method DeleteNote not implemented")
}
func (UnimplementedStorageServer) SearchNoteByName(context.Context, *wrapperspb.StringValue) (*SearchResponse, error) {
	return nil, status1.Errorf(codes.Unimplemented, "method SearchNoteByName not implemented")
}
func (UnimplementedStorageServer) SearchNoteByBody(context.Context, *wrapperspb.StringValue) (*SearchResponse, error) {
	return nil, status1.Errorf(codes.Unimplemented, "method SearchNoteByBody not implemented")
}
func (UnimplementedStorageServer) SearchDir(context.Context, *wrapperspb.StringValue) (*SearchResponse, error) {
	return nil, status1.Errorf(codes.Unimplemented, "method SearchDir not implemented")
}
func (UnimplementedStorageServer) mustEmbedUnimplementedStorageServer() {}

// UnsafeStorageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServer will
// result in compilation errors.
type UnsafeStorageServer interface {
	mustEmbedUnimplementedStorageServer()
}

func RegisterStorageServer(s grpc.ServiceRegistrar, srv StorageServer) {
	s.RegisterService(&Storage_ServiceDesc, srv)
}

func _Storage_GetNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.Int32Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Storage/GetNote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetNote(ctx, req.(*wrapperspb.Int32Value))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.Int32Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Storage/GetDir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetDir(ctx, req.(*wrapperspb.Int32Value))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_CreateNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Note)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).CreateNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Storage/CreateNote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).CreateNote(ctx, req.(*Note))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_UpdateNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoteUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).UpdateNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Storage/UpdateNote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).UpdateNote(ctx, req.(*NoteUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_CreateDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Dir)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).CreateDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Storage/CreateDir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).CreateDir(ctx, req.(*Dir))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_DeleteDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.Int32Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).DeleteDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Storage/DeleteDir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).DeleteDir(ctx, req.(*wrapperspb.Int32Value))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_DeleteNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.Int32Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).DeleteNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Storage/DeleteNote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).DeleteNote(ctx, req.(*wrapperspb.Int32Value))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_SearchNoteByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).SearchNoteByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Storage/SearchNoteByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).SearchNoteByName(ctx, req.(*wrapperspb.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_SearchNoteByBody_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).SearchNoteByBody(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Storage/SearchNoteByBody",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).SearchNoteByBody(ctx, req.(*wrapperspb.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_SearchDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).SearchDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Storage/SearchDir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).SearchDir(ctx, req.(*wrapperspb.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

// Storage_ServiceDesc is the grpc.ServiceDesc for Storage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Storage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Storage",
	HandlerType: (*StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNote",
			Handler:    _Storage_GetNote_Handler,
		},
		{
			MethodName: "GetDir",
			Handler:    _Storage_GetDir_Handler,
		},
		{
			MethodName: "CreateNote",
			Handler:    _Storage_CreateNote_Handler,
		},
		{
			MethodName: "UpdateNote",
			Handler:    _Storage_UpdateNote_Handler,
		},
		{
			MethodName: "CreateDir",
			Handler:    _Storage_CreateDir_Handler,
		},
		{
			MethodName: "DeleteDir",
			Handler:    _Storage_DeleteDir_Handler,
		},
		{
			MethodName: "DeleteNote",
			Handler:    _Storage_DeleteNote_Handler,
		},
		{
			MethodName: "SearchNoteByName",
			Handler:    _Storage_SearchNoteByName_Handler,
		},
		{
			MethodName: "SearchNoteByBody",
			Handler:    _Storage_SearchNoteByBody_Handler,
		},
		{
			MethodName: "SearchDir",
			Handler:    _Storage_SearchDir_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage/storage.proto",
}
