# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recognizer/recognizer.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1brecognizer/recognizer.proto\" \n\x10ImageToRecognize\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"$\n\x14ImagesArrToRecognize\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x0c\"\"\n\x10RecognizedResult\x12\x0e\n\x06result\x18\x01 \x01(\t2\xc3\x01\n\nRecognizer\x12:\n\x10RecognizeFormula\x12\x11.ImageToRecognize\x1a\x11.RecognizedResult\"\x00\x12<\n\x0eRecognizeMixed\x12\x15.ImagesArrToRecognize\x1a\x11.RecognizedResult\"\x00\x12;\n\rRecognizeText\x12\x15.ImagesArrToRecognize\x1a\x11.RecognizedResult\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recognizer.recognizer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGETORECOGNIZE']._serialized_start=31
  _globals['_IMAGETORECOGNIZE']._serialized_end=63
  _globals['_IMAGESARRTORECOGNIZE']._serialized_start=65
  _globals['_IMAGESARRTORECOGNIZE']._serialized_end=101
  _globals['_RECOGNIZEDRESULT']._serialized_start=103
  _globals['_RECOGNIZEDRESULT']._serialized_end=137
  _globals['_RECOGNIZER']._serialized_start=140
  _globals['_RECOGNIZER']._serialized_end=335
# @@protoc_insertion_point(module_scope)
