# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import recognizer_pb2 as recognizer_dot_recognizer__pb2


class RecognizerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecognizeFormula = channel.unary_unary(
                '/Recognizer/RecognizeFormula',
                request_serializer=recognizer_dot_recognizer__pb2.ImageToRecognize.SerializeToString,
                response_deserializer=recognizer_dot_recognizer__pb2.RecognizedResult.FromString,
                )
        self.RecognizeMixed = channel.unary_unary(
                '/Recognizer/RecognizeMixed',
                request_serializer=recognizer_dot_recognizer__pb2.ImagesArrToRecognize.SerializeToString,
                response_deserializer=recognizer_dot_recognizer__pb2.RecognizedResult.FromString,
                )
        self.RecognizeText = channel.unary_unary(
                '/Recognizer/RecognizeText',
                request_serializer=recognizer_dot_recognizer__pb2.ImagesArrToRecognize.SerializeToString,
                response_deserializer=recognizer_dot_recognizer__pb2.RecognizedResult.FromString,
                )


class RecognizerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecognizeFormula(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeMixed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecognizerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecognizeFormula': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeFormula,
                    request_deserializer=recognizer_dot_recognizer__pb2.ImageToRecognize.FromString,
                    response_serializer=recognizer_dot_recognizer__pb2.RecognizedResult.SerializeToString,
            ),
            'RecognizeMixed': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeMixed,
                    request_deserializer=recognizer_dot_recognizer__pb2.ImagesArrToRecognize.FromString,
                    response_serializer=recognizer_dot_recognizer__pb2.RecognizedResult.SerializeToString,
            ),
            'RecognizeText': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeText,
                    request_deserializer=recognizer_dot_recognizer__pb2.ImagesArrToRecognize.FromString,
                    response_serializer=recognizer_dot_recognizer__pb2.RecognizedResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Recognizer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Recognizer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecognizeFormula(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recognizer/RecognizeFormula',
            recognizer_dot_recognizer__pb2.ImageToRecognize.SerializeToString,
            recognizer_dot_recognizer__pb2.RecognizedResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RecognizeMixed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recognizer/RecognizeMixed',
            recognizer_dot_recognizer__pb2.ImagesArrToRecognize.SerializeToString,
            recognizer_dot_recognizer__pb2.RecognizedResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RecognizeText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recognizer/RecognizeText',
            recognizer_dot_recognizer__pb2.ImagesArrToRecognize.SerializeToString,
            recognizer_dot_recognizer__pb2.RecognizedResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
