---
version: '3.8'
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ${NGINX_CONFIF_PATH}:/etc/nginx/nginx.conf
      - ${NGINX_SSL_CERT_PATH}:/etc/cert.pem
      - ${NGINX_SSL_KEY_PATH}:/etc/key.pem
    ports: ['${NGINX_HTTP_PORT}:80', '${NGINX_HTTPS_PORT}:443']
    depends_on: [backend]
    networks: [backend, swagger]
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    networks: [backend, redis, postgres]
  swagger:
    container_name: swagger
    image: swaggerapi/swagger-ui
    environment: [SWAGGER_JSON=/docs/swagger.yml]
    volumes: [./docs:/docs]
    networks: [swagger]
  redis:
    container_name: redis
    image: redis:7.2.4
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
  postgres:
    container_name: postgres
    image: bitnami/postgresql:15.6.0
    volumes:
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /mnt/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
networks:
  backend:
    driver: bridge
  swagger:
    driver: bridge
  redis:
    driver: bridge
  postgres:
    driver: bridge
