---
version: '3.8'
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/nginx.conf
      - ${NGINX_SSL_CERT_PATH}:/etc/cert.pem
      - ${NGINX_SSL_KEY_PATH}:/etc/key.pem
    ports: ['${NGINX_HTTP_PORT}:80', '${NGINX_HTTPS_PORT}:443']
    depends_on: [backend]
    networks: [backend, swagger]
    restart: always
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    environment: ['DB_URL=${DB_URL}', 'PORT=${PORT}}']
    networks: [backend]
    depends_on: [postgres, redis]
    restart: always
  swagger:
    container_name: swagger
    image: swaggerapi/swagger-ui
    environment: [SWAGGER_JSON=/docs/swagger.yml]
    volumes: [./docs:/docs]
    networks: [swagger]
  redis:
    container_name: redis
    image: redis:7.2.4
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
    networks: [backend]
  postgres:
    container_name: postgres
    image: postgres:16
    volumes:
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init1.sql
      - ./scripts/postgres/default_user.sql:/docker-entrypoint-initdb.d/init2.sql
      - ./scripts/postgres/default_dir.sql:/docker-entrypoint-initdb.d/init3.sql
      - ./scripts/postgres/default_note.sql:/docker-entrypoint-initdb.d/init4.sql
      - /mnt/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks: [backend]
networks:
  backend:
    driver: bridge
  swagger:
    driver: bridge
