INSERT INTO snippets (name, description, body, user_id)
VALUES ('integral', 'Определенный интеграл', '`$$\int_{a}^{b}{}$$`', NULL),
       ('sum', 'Знак суммирования', '`$$\sum_{}^{}{}$$`', NULL),
       ('lim', 'Знак предела', '`$$\lim_{}{}$$`', NULL),
       ('alpha', 'Греческая бука альфа', '`$$\alpha$$`', NULL),
       ('beta', 'Греческая бука альфа', '`$$\beta$$`', NULL),
       ('theta', 'Греческая бука тета', '`$$\teta$$`', NULL),
       ('vector', 'Обозначение вектора', '`$$\vec{}$$`', NULL),
       ('matrix', 'Матрица', '```katex\n\begin{pmatrix}\na & b \\\nc & d\n\end{pmatrix}\n```', NULL),
       ('frac', 'Дробь с числителем и знаменателем', '`$$\frac{numerator}{denominator}$$`', NULL),
       ('sin', 'Синус', '`$$\sin{}$$`', NULL),
       ('cos', 'Косинус', '`$$\cos{}$$`', NULL),
       ('tan', 'Тангенс', '`$$\tan{}$$`', NULL),
       ('cot', 'Котангенс', '`$$\cot{}$$`', NULL),
       ('sec', 'Секанс', '`$$\sec{}$$`', NULL),
       ('csc', 'Косеканс', '`$$\csc{}$$`', NULL),
       ('log', 'Логарифм', '`$$\log{}$$`', NULL),
       ('ln', 'Натуральный логарифм', '`$$\ln{}$$`', NULL),
       ('exp', 'Экспонента', '`$$\exp{}$$`', NULL),
       ('lim', 'Предел', '`$$\lim_{}{}$$`', NULL),
       ('liminf', 'Предел инфимума', '`$$\liminf{}$$`', NULL),
       ('limsup', 'Предел супремума', '`$$\limsup{}$$`', NULL),
       ('max', 'Максимум', '`$$\max{}$$`', NULL),
       ('min', 'Минимум', '`$$\min{}$$`', NULL),
       ('gcd', 'Наибольший общий делитель', '`$$\gcd{}$$`', NULL),
       ('lcm', 'Наименьшее общее кратное', '`$$\operatorname{lcm}{}$$`', NULL),
       ('mod', 'Остаток от деления', '`$$\operatorname{mod}{}$$`', NULL),
       ('arg', 'Аргумент', '`$$\arg{}$$`', NULL),
       ('Im', 'Мнимая часть', '`$$\operatorname{Im}{}$$`', NULL),
       ('Re', 'Действительная часть', '`$$\operatorname{Re}{}$$`', NULL),
       ('floor', 'Наибольшее целое число', '`$$\lfloor{}\rfloor$$`', NULL),
       ('ceil', 'Наименьшее целое число', '`$$\lceil{}\rceil$$`', NULL),
       ('sqrt', 'Квадратный корень', '`$$\sqrt{}$$`', NULL),
       ('pm', 'Знак плюс-минус', '`$$\pm$$`', NULL),
       ('neq', 'Неравенство', '`$$\neq$$`', NULL),
       ('infty', 'Бесконечность', '`$$\infty$$`', NULL),
       ('forall', 'Квантор всеобщности', '`$$\forall$$`', NULL),
       ('exists', 'Квантор существования', '`$$\exists$$`', NULL),
       ('rightarrow', 'Вывод', '`$$\Rightarrow$$`', NULL),
       ('approx', 'Приблизительно равно', '`$$\approx$$`', NULL),
       ('emptyset', 'Пустое множество', '`$$\emptyset$$`', NULL);
